Unit4/Unit4/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Unit4.Data;
using Unit4.Models;

namespace Unit4.Controllers
{
    public class booksController : Controller
    {
        private readonly Unit4Context _context;

        public booksController(Unit4Context context)
        {
            _context = context;
        }
     


        // GET: books
        public async Task<IActionResult> Index()
        { 
              return _context.book != null ? 
                          View(await _context.book.ToListAsync()) :
                          Problem("Entity set 'Unit4Context.book'  is null.");
        }
        public async Task<IActionResult> Index1()
        {
            return _context.book != null ?
                        View(await _context.book.ToListAsync()) :
                        Problem("Entity set 'Unit4Context.book'  is null.");
        }
        public async Task<IActionResult> Catelog()
        {
            return _context.book != null ?
                View(await _context.book.ToListAsync()) :
                Problem("Entity set 'Unit4Context.book' is null");
        }
        public async Task<IActionResult> orderdetails()
        {
            var orItems = await _context.orderdetail.FromSqlRaw("select orders.Id as id, name as customer, title as booktitle, orders.quantity as quantity from book, orders, usersaccounts  where book.id = orders.bookid and orders.custid = usersaccounts.id  ").ToListAsync();
            return View(orItems);
        }

        public async Task<IActionResult> search()
        {
            List<book> brBook = new List<book>();
            return View(brBook);
        }

        // POST: items/search
        [HttpPost]
        public async Task<IActionResult> search(string s)
        {
            var brBook = await _context.book.FromSqlRaw("select * from book where info LIKE '%" + s + "%' ").ToListAsync();
            return View(brBook);
        }


        // GET: books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.book == null)
            {
                return NotFound();
            }

            var book = await _context.book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: books/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IFormFile file, [Bind("Id,title,info,price,discount,pubdate,category,bookquantity")] book book)
        {
            {
                if (file != null)
                {
                    string filename = file.FileName;
                    //  string  ext = Path.GetExtension(file.FileName);
                    string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                    using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                    { await file.CopyToAsync(filestream); }

                    book.imgfile = filename;
                }

                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        
        return View(book);
        }

        // GET: books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.book == null)
            {
                return NotFound();
            }

            var book = await _context.book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormFile file, int id, [Bind("Id,title,info,price,discount,pubdate,category,bookquantity,imgfile")] book book)
        {
            if (id != book.Id)
            { return NotFound(); }

            if (file != null)
            {
                string filename = file.FileName;
                //  string  ext = Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                { await file.CopyToAsync(filestream); }

                book.imgfile = filename;
            }
            _context.Update(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

           
        }


        // GET: books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.book == null)
            {
                return NotFound();
            }

            var book = await _context.book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.book == null)
            {
                return Problem("Entity set 'Unit4Context.book'  is null.");
            }
            var book = await _context.book.FindAsync(id);
            if (book != null)
            {
                _context.book.Remove(book);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool bookExists(int id)
        {
          return (_context.book?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> searchall()
        {

            {
                book brItem = new book();

                return View(brItem);
            }
        }

        [HttpPost]

        public async Task<IActionResult> SearchAll(string tit)
        {
            var bkItems = await _context.book.FromSqlRaw("select * from book where title = '" + tit + "' ").FirstOrDefaultAsync();

            return View(bkItems);
        }


    }

}

Unit4/Unit4/Controllers/ordersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Unit4.Data;
using Unit4.Models;

namespace Unit4.Controllers
{
    public class ordersController : Controller
    {
        private readonly Unit4Context _context;

        public ordersController(Unit4Context context)
        {
            _context = context;
        }

        // GET: orders
        public async Task<IActionResult> Index()
        {
            ViewData["role"] = HttpContext.Session.GetString("Role");
            return _context.orders != null ?
                          View(await _context.orders.ToListAsync()) :
                          Problem("Entity set 'Unit4Context.orders'  is null.");
        }

        // GET: orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // GET: orders/Buy
        public async Task<IActionResult> Buy(int? id)
        {
            string ss = HttpContext.Session.GetString("Role");

            if (ss == "customer")
            {
                var book = await _context.book.FindAsync(id);
                return View(book);
            }
            else
                return RedirectToAction("Warning", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Buy(int bookId, int quantity)
        {
            orders order = new orders();
            order.bookid = bookId;
            order.quantity = quantity;
            order.custid = Convert.ToInt32(HttpContext.Session.GetString("userid"));
            order.buydate = DateTime.Today;
            var builder = WebApplication.CreateBuilder();
            string conStr = builder.Configuration.GetConnectionString("Unit4Context");
            SqlConnection conn = new SqlConnection(conStr);
            string sql;
            int qt = 0;
            sql = "select * from book where (id ='" + order.bookid + "' )";
            SqlCommand comm = new SqlCommand(sql, conn);
            conn.Open();
            SqlDataReader reader = comm.ExecuteReader();
            if (reader.Read())
            {
                qt = (int)reader["bookquantity"]; // store quantity
            }
            reader.Close();
            conn.Close();
            if (order.quantity > qt)
            {
                ViewData["message"] = "maxiumam order quantity sould be " + qt;
                var book = await _context.book.FindAsync(bookId);
                return View(book);
            }
            else
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                sql = "UPDATE book  SET bookquantity  = bookquantity   - '" + order.quantity + "'  where (id ='" + order.bookid + "' )";
                comm = new SqlCommand(sql, conn);
                conn.Open();
                comm.ExecuteNonQuery();
                conn.Close();
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,bookid,custid,quantity,buydate")] orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(orders);
        }

        // GET: orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            return View(orders);
        }

        // POST: orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,bookid,custid,quantity,buydate")] orders orders)
        {
            if (id != orders.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ordersExists(orders.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(orders);
        }

        // GET: orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.orders == null)
            {
                return Problem("Entity set 'Unit4Context.orders'  is null.");
            }
            var orders = await _context.orders.FindAsync(id);
            if (orders != null)
            {
                _context.orders.Remove(orders);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ordersExists(int id)
        {
            return (_context.orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Unit4/Unit4/Views/books/Catelog.cshtml
@model IEnumerable<Unit4.Models.book>
<div class="container-fluid">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        @item.title
                    </div>
                    <div class="card-body">
                        <img src="~/images/@item.imgfile" height="150"/>
                    </div>
                    <div class="card-footer">
                        <div class="card-footer">
                            <a asp-controller="orders" asp-action="Buy" asp-route-id="@item.Id">Buy</a>
                        </div>
                        |
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Unit4/Unit4/Views/books/Edit.cshtml
@model Unit4.Models.book

@{
    ViewData["Title"] = "Edit";
}

<form asp-action="Edit" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="title" class="control-label"></label>
        <input asp-for="title" class="form-control" />
        <span asp-validation-for="title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="info" class="control-label"></label>
        <input asp-for="info" class="form-control" />
        <span asp-validation-for="info" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="price" class="control-label"></label>
        <input asp-for="price" class="form-control" />
        <span asp-validation-for="price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="discount" class="control-label"></label>
        <div class="checkbox">
            <label> <input type="radio" asp-for="discount" value="yes" /> Yes</label>
        </div>
        <div class="checkbox">
            <label> <input type="radio" asp-for="discount" value="no" />No</label>
        </div>
        <span asp-validation-for="discount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="pubdate" class="control-label"></label>
        <input asp-for="pubdate" class="form-control" />
        <span asp-validation-for="pubdate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Catagory</label>
        <select class="form-control" asp-for="category">
            <option value="0">Please select</option>
            <option value="1">CS</option>
            <option value="2">IS</option>
        </select>
        <span asp-validation-for="category" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="bookquantity" class="control-label"></label>
        <input asp-for="bookquantity" class="form-control" />
        <span asp-validation-for="bookquantity" class="text-danger"></span>
    </div>
    <img src="~/images/@Model.imgfile" height="150" />
    <div class="form-group">
        <label asp-for="imgfile" class="control-label"></label>
        <input asp-for="imgfile" class="form-control" />
        <label class="control-label">Pic</label>
        <input type="file" class="form-control" name="file" />
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>


<div>
    <a asp-action="Index">Back to List</a>
</div>

Unit4/Unit4/Views/books/Index.cshtml
@model IEnumerable<Unit4.Models.book>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="Search">Search</a>
</p>
<p>
    <a asp-action="Searchall">Searchall</a>
</p>
<head> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<div id="myCarousel" style="width:30% ; min-width:300px " class="carousel slide mx-auto" data-ride="carousel">
        <div class="carousel-inner" id="demo"> 
@{
    var counter = 0;            
}
@foreach (var item in Model)
{
           <div class='carousel-item   @(counter == 0 ? "active"  : String.Empty)'   > 
              <center> <img src="~/images/@item.imgfile" height="150"> </center>
                <div class='carousel-caption mx-auto'  style='top:45%; left:15%;' >
                 <h3 style='width:100px' class='mx-auto bg-secondary  text-white'>  @item.price SR  </h3>
                  <h6 style='width:100px' class='mx-auto bg-light  text-white'>  <a asp-action="Details" asp-route-id="@item.Id">Details</a>  </h6>
                    
                </div> 
            </div> 
            counter++;
}
        </div>
        <a class="carousel-control-prev " href="#myCarousel" data-slide="prev">
            <span class="carousel-control-prev-icon bg-secondary"></span> </a>
        <a class="carousel-control-next" href="#myCarousel" data-slide="next">
            <span class="carousel-control-next-icon bg-secondary"></span></a>
 </div>
 <br />
<div class="container-fluid">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        @item.title
                    </div>
                    <div class="card-body">
                        <img src="~/images/@item.imgfile" height="150" />
                    </div>
                    <div class="card-footer">
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                        
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Unit4/Unit4/Views/books/index1.cshtml
@model IEnumerable<Unit4.Models.book>

@{
    ViewData["Title"] = "index1";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<h1>index1</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.info)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.discount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pubdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bookquantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.imgfile)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.info)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.discount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pubdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bookquantity)
            </td>
            <td>
              
                  
                        <dd class="col-sm-10">
                            <img src="~/images/@item.imgfile" height="150" />
                            
                        </dd>
                    
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>