Web2 Luctures/Projects/Projects/Controllers/ordersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Projects.Data;
using Projects.Models;

namespace Projects.Controllers
{
    public class ordersController : Controller
    {
        private readonly ProjectsContext _context;

        public ordersController(ProjectsContext context)
        {
            _context = context;
        }

        // GET: orders
        public async Task<IActionResult> Index()
        {
              return _context.orders != null ? 
                          View(await _context.orders.ToListAsync()) :
                          Problem("Entity set 'ProjectsContext.orders'  is null.");
        }
        public async Task<IActionResult> Buy(int? id)
        {
                var book = await _context.book.FindAsync(id);
                return View(book);
        
        }
        [HttpPost]
        public async Task<IActionResult> Buy(int bookId, int quantity)
        {
            orders order = new orders();
            order.bookId = bookId;
            order.quantity = quantity;
            order.userid = Convert.ToInt32(HttpContext.Session.GetString("userid"));
            order.buydate = DateTime.Today;
            var builder = WebApplication.CreateBuilder();
            string conStr = builder.Configuration.GetConnectionString("ProjectsContext");
            SqlConnection conn = new SqlConnection(conStr);
            string sql;
            int qt = 0;
            sql = "select * from book where (id ='" + order.bookId + "' )";
            SqlCommand comm = new SqlCommand(sql, conn);
            conn.Open();
            SqlDataReader reader = comm.ExecuteReader();
            if (reader.Read())
            {
                qt = (int)reader["quantity"]; // store quantity
            }
            reader.Close();
            conn.Close();
            if (order.quantity > qt)
            {
                ViewData["message"] = "maxiumam order quantity sould be " + qt;
                var book = await _context.book.FindAsync(bookId);
                return View(book);
            }
            else
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                sql = "UPDATE book  SET quantity  = quantity   - '" + order.quantity + "'  where (id ='" + order.bookId + "' )";
                comm = new SqlCommand(sql, conn);
                conn.Open();
                comm.ExecuteNonQuery();
                conn.Close();
                return RedirectToAction(nameof(myorders));
            }
        }


        public async Task<IActionResult> ordersdetail(int? id)
        {
            var orItems = await _context.ordersdetail
       .FromSqlRaw($"select (CASE WHEN book.discount = 'yes' THEN CAST(orders.quantity * (book.price * 0.9) AS INT) ELSE orders.quantity * book.price END) AS totalprice, " +
                   "orders.id, orders.bookid, orders.Buydate, orders.quantity, orders.userid, usersaccounts.name AS username " +
                   $"from orders, book, usersaccounts where orders.userid='{id}' and book.id=orders.bookid and usersaccounts.id={id}")
       .ToListAsync();


            return View(orItems);
        }




        public async Task<IActionResult> myorders()

        {
            int id = Convert.ToInt32(HttpContext.Session.GetString("userid"));
            var orItems = await _context.ordersdetail
                   .FromSqlRaw($"select (CASE WHEN book.discount = 'yes' THEN CAST(orders.quantity * (book.price * 0.9) AS INT) ELSE orders.quantity * book.price END) AS totalprice, " +
                               "orders.id, orders.bookid, orders.Buydate, orders.quantity, orders.userid, book.name AS username " +
                               $"from orders, book, usersaccounts where orders.userid='{id}' and book.id=orders.bookid and usersaccounts.id={id}")
                   .ToListAsync();


            return View(orItems);


        }





        public async Task<IActionResult> customerOrders(int? id)

        {
            int userid = Convert.ToInt32(HttpContext.Session.GetString("userid"));
            var orItems = await _context.orders.FromSqlRaw("select *  from orders where  userid = '" + id + "'  ").ToListAsync();

            return View(orItems);


        }


        public async Task<IActionResult> customerreport()
         {
          var orItems = await _context.report
        .FromSqlRaw("SELECT usersaccounts.id AS Id, usersaccounts.name AS customername, SUM(orders.quantity * book.price) AS total " +
                    "FROM orders " +
                    "JOIN book ON orders.bookid = book.id " +
                    "JOIN usersaccounts ON orders.userid = usersaccounts.id " +
                    "GROUP BY usersaccounts.id, usersaccounts.name")
        .ToListAsync();

        return View(orItems);
         }



        // GET: orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }
        public async Task<IActionResult> Create(int? id)

        {

            var book = await _context.book.FindAsync(id);


            return View(book);

        }

        // GET: orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,bookId,userid,buydate,quantity")] orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(orders);
        }

        // GET: orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {   
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            return View(orders);
        }

        // POST: orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,bookId,userid,buydate,quantity")] orders orders)
        {
            if (id != orders.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ordersExists(orders.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(myorders));
            }
            return View(orders);
        }

        // GET: orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.orders == null)
            {
                return Problem("Entity set 'ProjectsContext.orders'  is null.");
            }
            var orders = await _context.orders.FindAsync(id);
            if (orders != null)
            {
                _context.orders.Remove(orders);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ordersExists(int id)
        {
          return (_context.orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Web2 Luctures/Projects/Projects/Controllers/usersaccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Projects.Data;
using Projects.Models;

namespace Projects.Controllers
{
    public class usersaccountsController : Controller
    {
        private readonly ProjectsContext _context;

        public usersaccountsController(ProjectsContext context)
        {
            _context = context;
        }

        // GET: useraccounts
        public async Task<IActionResult> Index()
        {
              return _context.usersaccounts != null ? 
                          View(await _context.usersaccounts.ToListAsync()) :
                          Problem("Entity set 'ProjectsContext.useraccounts'  is null.");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("Name"); 
            HttpContext.Session.Remove("Role"); 

            HttpContext.Response.Cookies.Delete("Name"); 
            HttpContext.Response.Cookies.Delete("Role");

            return RedirectToAction(nameof(Login));
        }

        public async Task<IActionResult> email(int? id)
        {


            return View();
        }


        [HttpPost, ActionName("email")]
        [ValidateAntiForgeryToken]
        public IActionResult email(string address, string subject, string body)
        {
            SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");
            var mail = new MailMessage();
            mail.From = new MailAddress("homm9807@gmail.com");
            mail.To.Add(address); // receiver email address
            mail.Subject = subject;
            mail.IsBodyHtml = true;
            mail.Body = body;
            SmtpServer.Port = 587;
            SmtpServer.UseDefaultCredentials = false;
            SmtpServer.Credentials = new System.Net.NetworkCredential("homm9807@gmail.com", "mydjptatmcmypudn");
            SmtpServer.EnableSsl = true;
            SmtpServer.Send(mail);
            ViewData["Message"] = "Email sent.";
            return View();

        }


        public async Task<IActionResult> Detailsitems(int? id)
        {
            if (id == null || _context.book == null)
            {
                return NotFound();
            }

            var book = await _context.book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: useraccounts/Details/5


        // GET: useraccounts/Create
        public IActionResult Create()
        {
            return View();
        }
        // POST: Useralls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, name, pass, RegistDate")] usersaccounts useraccounts)
        {
       

            useraccounts.role = "customer";
            useraccounts.RegistDate = DateTime.Now;
                _context.Add(useraccounts);
                await _context.SaveChangesAsync();
            ViewData["added"] = "Added sucssefual";
            return RedirectToAction(nameof(login));
    
            
        }
        public IActionResult CreateAdmin()
        {
            return View();
        }
        // POST: Useralls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAdmin([Bind("Id, name, pass, RegistDate")] usersaccounts useraccounts)
        {

            useraccounts.role = "admin";
            useraccounts.RegistDate = DateTime.Now;
            _context.Add(useraccounts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(admin));


        }

        public IActionResult login()
        {
            if (!HttpContext.Request.Cookies.ContainsKey("Name"))

                return View();
            else
            {
                string na = HttpContext.Request.Cookies["Name"].ToString();
                string ro = HttpContext.Request.Cookies["Role"].ToString();
                HttpContext.Session.SetString("Name", na);
                HttpContext.Session.SetString("Role", ro);

                if (ro == "admin")
                {
                    return RedirectToAction(nameof(admin));

                }
                return RedirectToAction(nameof(customer));
            }
        
        }

        [HttpPost, ActionName("login")]
        public async Task<IActionResult> Login(string na, string pa, string auto)
        {
            SqlConnection conn1 = new SqlConnection("Data Source =.\\sqlexpress; Initial Catalog = final; Integrated Security = True; Pooling = False");
            string sql;
            sql = "SELECT * FROM usersaccounts where name ='" + na + "' and  pass ='" + pa + "' ";
            SqlCommand comm = new SqlCommand(sql, conn1);
            conn1.Open();
            SqlDataReader reader = comm.ExecuteReader();

            if (reader.Read())
            {
                string na1 = (string)reader["name"];
                string ro = (string)reader["role"];
                int userid = (int)reader["id"];
                HttpContext.Session.SetString("Name", na1);
                HttpContext.Session.SetString("Role", ro);
                HttpContext.Session.SetString("userid", userid+"");

                reader.Close();
                conn1.Close();

                if (auto == "on")
                {
                    HttpContext.Response.Cookies.Append("Name", na1);
                    HttpContext.Response.Cookies.Append("Role", ro);
                }

                if (ro == "admin")
                {
                    return RedirectToAction(nameof(admin));
                }

                return RedirectToAction(nameof(customer));
            }
            else
            {
                ViewData["Message"] = "Wrong username or password";
                return View();
            }
        }





        public async Task<IActionResult> admin(int? id)
        {
            string ss = HttpContext.Session.GetString("Name");
            ViewData["admin"] = ss;
            return View();
        }

        public IActionResult customer(int? id)
        {
            string ss = HttpContext.Session.GetString("Name");
            ViewData["customer"] = ss;
            
            return View(_context.book.Where(k => k.discount == "yes"));
        }

        public async Task<IActionResult> searchall()
        {
            {
                usersaccounts brItem = new usersaccounts();

                return View(brItem);
            }
        }

        [HttpPost]
        public async Task<IActionResult> searchall(string role,string name)
        {
            var usItems = await _context.usersaccounts.FromSqlRaw("select * from usersaccounts where name = '" + name + "' ").FirstOrDefaultAsync();

            return View(usItems);
        }



        // GET: useraccounts/Edit/5
        public async Task<IActionResult> Edit()
        {
            int id = Convert.ToInt32(HttpContext.Session.GetString("userid"));
            var useraccounts = await _context.usersaccounts.FindAsync(id);
            return View(useraccounts);
        }

        // POST: useraccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,name,pass,role,RegistDate")] usersaccounts useraccounts)
        {
         
                {
                    _context.Update(useraccounts);
                    await _context.SaveChangesAsync();
                }
               
                return RedirectToAction(nameof(login));
           
        }

        // GET: useraccounts/Delete/5
        

        private bool useraccountsExists(int id)
        {
          return (_context.usersaccounts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Web2 Luctures/Projects/Projects/Views/orders/Buy.cshtml
@model Projects.Models.book
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@{
    ViewData["Title"] = "Buy";
    Layout = "~/Views/Shared/_LayoutCustomer.cshtml";
}

<h1>Buy</h1>

<div>
    <h4>book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.descr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.descr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.discount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.discount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.imgfile)
        </dt>
        <dd class="col-sm-10">
            <img src="~/images/@Model.imgfile" height="150" />
            <br />
        </dd>
    </dl>
</div>
<p style="color:red"> @ViewData["message"]</p>
<form asp-action="Buy">
    <input type="hidden" name="bookId" value=@Model.Id />
    <div class="form-group">
        <label for="quantity" class="control-label">Quantity</label>
        <input name="quantity" class="form-control" id="qu" onchange="gettotal()" />

    </div>
    <input type="submit" value="Buy" class="btn btn-primary" />
    <div id="message"></div>
</form>
@section scripts{
    <script>
        function gettotal() {
            tot = 0;

            var q = document.getElementById('qu').value;
            var pr = '@Model.price';
            tot = q * pr;
            if ('@Model.discount' == "yes") {
                tot = (tot * 90) / 100
            }
            Swal.fire({ icon: 'success', title: "total  =" + tot, showConfirmButton: false, timer: 2500 })
        }
    </script>
}
<a asp-controller="usersaccounts" asp-action="customer">Back to Home</a>

Web2 Luctures/Projects/Projects/Views/orders/Create.cshtml
@model Projects.Models.orders

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>orders</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="bookId" class="control-label"></label>
                <input asp-for="bookId" class="form-control" />
                <span asp-validation-for="bookId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userid" class="control-label"></label>
                <input asp-for="userid" class="form-control" />
                <span asp-validation-for="userid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="buydate" class="control-label"></label>
                <input asp-for="buydate" class="form-control" />
                <span asp-validation-for="buydate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Web2 Luctures/Projects/Projects/Views/orders/Delete.cshtml
@model Projects.Models.orders

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>orders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.bookId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.bookId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.buydate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.buydate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web2 Luctures/Projects/Projects/Views/orders/Details.cshtml
@model Projects.Models.orders

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>orders</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.bookId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.bookId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.buydate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.buydate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="customerreport">Back to List</a>
</div>

Web2 Luctures/Projects/Projects/Views/orders/Edit.cshtml
@model Projects.Models.orders

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>orders</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="bookId" />

            <input type="hidden" asp-for="userid" />

            <input type="hidden" asp-for="buydate" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Web2 Luctures/Projects/Projects/Views/orders/Index.cshtml
@model IEnumerable<Projects.Models.orders>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.bookId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.userid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.buydate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.bookId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.userid)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.buydate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Web2 Luctures/Projects/Projects/Views/orders/customerOrders.cshtml
@model IEnumerable<Projects.Models.orders>

@{
    ViewData["Title"] = "customerOrders";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>customerOrders</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.bookId)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.buydate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.bookId)
            </td>
          
            <td>
                @Html.DisplayFor(modelItem => item.buydate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
           
        </tr>
}
    </tbody>
</table>

Web2 Luctures/Projects/Projects/Views/orders/customerreport.cshtml
@model IEnumerable<Projects.Models.report>

@{
    ViewData["Title"] = "customerreport";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>customerreport</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.customername)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total)
            </th>
            <th>
                Details
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.customername)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.total)
            </td>
            <td>
                    <a asp-action="ordersdetail" asp-route-id="@item.Id">View</a>
            </td>
        </tr>
}
    </tbody>
</table>

Web2 Luctures/Projects/Projects/Views/orders/myorders.cshtml
@model IEnumerable<Projects.Models.orderdetail>

@{
    ViewData["Title"] = "myorders";
    Layout = "~/Views/Shared/_LayoutCustomer.cshtml";
}

<h1>My Purchase</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.totalprice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.buydate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.totalprice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.buydate)
            </td>
           
        </tr>
}
    </tbody>
</table>

Web2 Luctures/Projects/Projects/Views/orders/ordersdetail.cshtml
@model IEnumerable<Projects.Models.orderdetail>

@{
    ViewData["Title"] = "ordersdetail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Your Orders Details</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.totalprice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.buydate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.totalprice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.buydate)
            </td>
            
        </tr>
}
    </tbody>
</table>